import type { WizardItem } from "@/shared/Wizards/WizardNav/WizardNav";
import {
  StepProduct,
  StepCustomer,
  StepOptions,
  StepPayment,
  StepConfirmation,
} from "./Steps";

export const productSteps: WizardItem[] = [
  {
    id: 1,
    label: "1",
    name: "",
    disabled: false,
    icon: "Info",
    title: "find your product",
    description: "some description",
    info: " extra info",
    element: <StepProduct />,
  },
    {
    id: 2,
    label: "2",
    name: "",
    disabled: false,
    icon: "Info",
    title: "find your product",
    description: "some description",
    info: " extra info",
    element: <StepOptions />,
  },
  {
    id: 3,
    label: "3",
    name: "",
    disabled: false,
    icon: "Info",
    title: "find your product",
    description: "some description",
    info: " extra info",
    element: <StepCustomer />,
  },
  {
    id: 4,
    label: "4",
    name: "",
    disabled: false,
    icon: "Info",
    title: "find your product",
    description: "some description",
    info: " extra info",
    element: <StepPayment />,
  },
  {
    id: 5,
    label: "5",
    name: "",
    disabled: false,
    icon: "Info",
    title: "find your product",
    description: "some description",
    info: " extra info",
    element: <StepConfirmation />,
  },
];
