import type { WizardItem } from "@/shared/Wizards/WizardNav/WizardNav";
import {
  StepProduct,
  StepCustomer,
  StepOptions,
  StepPayment,
  StepConfirmation,
} from "./Steps";

export const productSteps: WizardItem[] = [
  {
    id: 1,
    label: "Select Product",
    name: "",
    disabled: false,
    icon: "Package",
    title: "find your product",
    description: "some description",
    info: " extra info",
    element: <StepProduct />,
  },
    {
    id: 2,
    label: "Configure Options",
    name: "",
    disabled: false,
    icon: "Calculator",
    title: "find your product",
    description: "some description",
    info: " extra info",
    element: <StepOptions />,
  },
  {
    id: 3,
    label: "Customer Details",
    name: "",
    disabled: false,
    icon: "UserCircle",
    title: "find your product",
    description: "some description",
    info: " extra info",
    element: <StepCustomer />,
  },
  {
    id: 4,
    label: "Payment",
    name: "",
    disabled: false,
    icon: "CreditCard",
    title: "find your product",
    description: "some description",
    info: " extra info",
    element: <StepPayment />,
  },
  {
    id: 5,
    label: "Confirmation",
    name: "",
    disabled: false,
    icon: "Pen",
    title: "find your product",
    description: "some description",
    info: " extra info",
    element: <StepConfirmation />,
  },
];
